# Generated by Django 4.2.5 on 2023-11-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_subida_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subida',
            name='id_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
