# Generated by Django 4.2.5 on 2023-11-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
